### ISSUE TITLE
incorporate submodule for automated file transfer 

### ISSUE THREAD

**Issue by jpalmer37** [BCCDC-PHL/auto-hcv#1]
There's been talks about adding in a submodule within this program to handle the automatic transferring of select summary files to a separate storage location different from the final results folder. This could be a common use case where we only want to share select summary files (and not the detailed lower-level ones) to an accessible location where downstream users can view them. 

If this does not fit into the scope you envisioned for this project @dfornika, this can also be created as a separate entity. Would greatly appreciate feedback!

**Comment by dfornika** [comment]
I think that functionality could fit under a 'post_analysis' step. See the [auto-tb.post_analysis](https://github.com/BCCDC-PHL/auto-tb/blob/main/auto_tb/post_analysis.py) module.

**Comment by jpalmer37** [comment]
Good idea. Thanks for the guidance @dfornika. Mind taking a look now? I moved the transfer and the work directory cleanup to a new `post_analysis.py` script. 

I also ran a number of tests with a `dev-config.json`.
