### ISSUE TITLE
Write transferred outputs into timestamped sub-directory

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/auto-hcv#3]
To handle the use-case where we may want to transfer updated analysis outputs for a sequencing run that has already been transferred, consider writing the transferred outputs under a sub-directory that is named using a timestamp with format `YYYYMMDDHHmmss`

**Comment by jpalmer37** [comment]
Finished testing using a `dev-config.json` in directories under my home folder. I made the subfolders look like `YYYY-MM-DD_hh-mm-ss` for readability.


Feels ready to merge from my perspective. Let me know your thoughts @dfornika

**Comment by dfornika** [comment]
Fixed in #4
